export const PERMISSIONS = {
  // ── Admin ──────────────────────────────────────────
  ADMIN_COMPANY_READ: 'admin.company.read',
  ADMIN_COMPANY_UPDATE: 'admin.company.update',
  ADMIN_USER_READ: 'admin.user.read',
  ADMIN_USER_CREATE: 'admin.user.create',
  ADMIN_USER_UPDATE: 'admin.user.update',
  ADMIN_USER_DEACTIVATE: 'admin.user.deactivate',
  ADMIN_ROLE_READ: 'admin.role.read',
  ADMIN_ROLE_CREATE: 'admin.role.create',
  ADMIN_ROLE_UPDATE: 'admin.role.update',
  ADMIN_ROLE_DELETE: 'admin.role.delete',
  ADMIN_MASTER_READ: 'admin.master.read',
  ADMIN_MASTER_CREATE: 'admin.master.create',
  ADMIN_MASTER_UPDATE: 'admin.master.update',
  ADMIN_MASTER_DELETE: 'admin.master.delete',
  ADMIN_CUSTOM_FIELD_READ: 'admin.custom-field.read',
  ADMIN_CUSTOM_FIELD_CREATE: 'admin.custom-field.create',
  ADMIN_CUSTOM_FIELD_UPDATE: 'admin.custom-field.update',
  ADMIN_CUSTOM_FIELD_DELETE: 'admin.custom-field.delete',
  ADMIN_CONFIG_READ: 'admin.config.read',
  ADMIN_CONFIG_UPDATE: 'admin.config.update',
  ADMIN_AUDIT_READ: 'admin.audit.read',

  // ── Inventory ─────────────────────────────────────
  INVENTORY_PROJECT_READ: 'inventory.project.read',
  INVENTORY_PROJECT_CREATE: 'inventory.project.create',
  INVENTORY_PROJECT_UPDATE: 'inventory.project.update',
  INVENTORY_PROJECT_DELETE: 'inventory.project.delete',
  INVENTORY_TOWER_READ: 'inventory.tower.read',
  INVENTORY_TOWER_CREATE: 'inventory.tower.create',
  INVENTORY_TOWER_UPDATE: 'inventory.tower.update',
  INVENTORY_TOWER_DELETE: 'inventory.tower.delete',
  INVENTORY_UNIT_READ: 'inventory.unit.read',
  INVENTORY_UNIT_CREATE: 'inventory.unit.create',
  INVENTORY_UNIT_UPDATE: 'inventory.unit.update',
  INVENTORY_UNIT_BULK_GENERATE: 'inventory.unit.bulk-generate',
  INVENTORY_UNIT_IMPORT: 'inventory.unit.import',
  INVENTORY_UNIT_EXPORT: 'inventory.unit.export',
  INVENTORY_UNIT_HOLD: 'inventory.unit.hold',
  INVENTORY_UNIT_BOOK: 'inventory.unit.book',
  INVENTORY_UNIT_BLOCK: 'inventory.unit.block',
  INVENTORY_UNIT_ALLOT: 'inventory.unit.allot',
  INVENTORY_UNIT_REGISTER: 'inventory.unit.register',
  INVENTORY_UNIT_CANCEL: 'inventory.unit.cancel',
  INVENTORY_UNIT_RELEASE: 'inventory.unit.release',
  INVENTORY_RATE_READ: 'inventory.rate.read',
  INVENTORY_RATE_CHANGE: 'inventory.rate.change',
  INVENTORY_UPLOAD_READ: 'inventory.upload.read',
  INVENTORY_UPLOAD_CREATE: 'inventory.upload.create',
  INVENTORY_UPLOAD_DELETE: 'inventory.upload.delete',

  // ── Presales ───────────────────────────────────────
  PRESALES_APPLICANT_READ: 'presales.applicant.read',
  PRESALES_APPLICANT_CREATE: 'presales.applicant.create',
  PRESALES_APPLICANT_UPDATE: 'presales.applicant.update',
  PRESALES_APPLICANT_MERGE: 'presales.applicant.merge',
  PRESALES_INQUIRY_READ: 'presales.inquiry.read',
  PRESALES_INQUIRY_CREATE: 'presales.inquiry.create',
  PRESALES_INQUIRY_UPDATE: 'presales.inquiry.update',
  PRESALES_INQUIRY_DELETE: 'presales.inquiry.delete',
  PRESALES_INQUIRY_ASSIGN: 'presales.inquiry.assign',
  PRESALES_INQUIRY_IMPORT: 'presales.inquiry.import',
  PRESALES_FOLLOW_UP_READ: 'presales.follow-up.read',
  PRESALES_FOLLOW_UP_CREATE: 'presales.follow-up.create',
  PRESALES_FOLLOW_UP_UPDATE: 'presales.follow-up.update',
  PRESALES_SITE_VISIT_READ: 'presales.site-visit.read',
  PRESALES_SITE_VISIT_CREATE: 'presales.site-visit.create',
  PRESALES_SITE_VISIT_UPDATE: 'presales.site-visit.update',
  PRESALES_COMMUNICATION_SEND: 'presales.communication.send',
  PRESALES_ASSIGNMENT_POOL_MANAGE: 'presales.assignment-pool.manage',
  PRESALES_REPORT_VIEW: 'presales.report.view',

  // ── Postsales ──────────────────────────────────────
  POSTSALES_BOOKING_READ: 'postsales.booking.read',
  POSTSALES_BOOKING_CREATE: 'postsales.booking.create',
  POSTSALES_BOOKING_UPDATE: 'postsales.booking.update',
  POSTSALES_BOOKING_ALLOT: 'postsales.booking.allot',
  POSTSALES_BOOKING_REGISTER: 'postsales.booking.register',
  POSTSALES_BOOKING_CANCEL: 'postsales.booking.cancel',
  POSTSALES_PLAN_READ: 'postsales.plan.read',
  POSTSALES_PLAN_EDIT: 'postsales.plan.edit',
  POSTSALES_UNIT_READ: 'postsales.unit.read',
  POSTSALES_UNIT_UPDATE: 'postsales.unit.update',
  POSTSALES_DEMAND_READ: 'postsales.demand.read',
  POSTSALES_DEMAND_GENERATE: 'postsales.demand.generate',
  POSTSALES_RECEIPT_READ: 'postsales.receipt.read',
  POSTSALES_RECEIPT_CREATE: 'postsales.receipt.create',
  POSTSALES_RECEIPT_CANCEL: 'postsales.receipt.cancel',
  POSTSALES_CHEQUE_VERIFY: 'postsales.cheque.verify',
  POSTSALES_EXTRA_CHARGE_CREATE: 'postsales.extra-charge.create',
  POSTSALES_INTEREST_WAIVE: 'postsales.interest.waive',
  POSTSALES_TDS_READ: 'postsales.tds.read',
  POSTSALES_TDS_CERTIFICATE: 'postsales.tds.certificate',
  POSTSALES_TRANSFER_READ: 'postsales.transfer.read',
  POSTSALES_TRANSFER_CREATE: 'postsales.transfer.create',
  POSTSALES_TRANSFER_APPROVE: 'postsales.transfer.approve',
  POSTSALES_REFUND_REQUEST: 'postsales.refund.request',
  POSTSALES_REFUND_APPROVE: 'postsales.refund.approve',
  POSTSALES_REFUND_PAY: 'postsales.refund.pay',
  POSTSALES_DOCUMENT_READ: 'postsales.document.read',
  POSTSALES_DOCUMENT_UPLOAD: 'postsales.document.upload',
  POSTSALES_DOCUMENT_DELETE: 'postsales.document.delete',
  POSTSALES_LETTER_READ: 'postsales.letter.read',
  POSTSALES_LETTER_GENERATE: 'postsales.letter.generate',

  // ── Accounts ───────────────────────────────────────
  ACCOUNTS_RECEIPT_VERIFY: 'accounts.receipt.verify',
  ACCOUNTS_PAYMENT_READ: 'accounts.payment.read',
  ACCOUNTS_PAYMENT_CREATE: 'accounts.payment.create',
  ACCOUNTS_COMMISSION_READ: 'accounts.commission.read',
  ACCOUNTS_COMMISSION_APPROVE: 'accounts.commission.approve',

  // ── Reports ────────────────────────────────────────
  REPORTS_SALES_VIEW: 'reports.sales.view',
  REPORTS_COLLECTION_VIEW: 'reports.collection.view',
  REPORTS_OUTSTANDING_VIEW: 'reports.outstanding.view',
  REPORTS_BROKER_VIEW: 'reports.broker.view',
  REPORTS_GST_VIEW: 'reports.gst.view',
  REPORTS_CUSTOM_CREATE: 'reports.custom.create',

  // ── Portal ─────────────────────────────────────────
  PORTAL_BOOKING_READ: 'portal.booking.read',
  PORTAL_RECEIPT_READ: 'portal.receipt.read',
  PORTAL_DOCUMENT_READ: 'portal.document.read',
  PORTAL_DOCUMENT_UPLOAD: 'portal.document.upload',
  PORTAL_PAYMENT_SCHEDULE_READ: 'portal.payment-schedule.read',
  PORTAL_PROFILE_UPDATE: 'portal.profile.update',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export const PERMISSION_MODULES = [
  'admin',
  'inventory',
  'presales',
  'postsales',
  'accounts',
  'reports',
  'portal',
] as const;

export type PermissionModule = (typeof PERMISSION_MODULES)[number];
