#!/usr/bin/env bash
# Creates the OpenEstate database and the two application Postgres roles
# (openestate_app, openestate_system) against a PostgreSQL server the admin
# already runs. Never installs, configures, or manages PostgreSQL itself —
# only connects to it. Safe to re-run: every statement checks existence
# first (matches deploy/docker/init-db/01-create-app-role.sh's pattern,
# ported to run outside a docker-entrypoint-initdb.d fresh-cluster context,
# so it also has to create the database itself, which the Docker image did
# implicitly via POSTGRES_DB).
set -euo pipefail

log()  { printf '\033[1;32m[setup-database]\033[0m %s\n' "$1"; }
warn() { printf '\033[1;33m[setup-database]\033[0m %s\n' "$1"; }
die()  { printf '\033[1;31m[setup-database]\033[0m %s\n' "$1" >&2; exit 1; }

PG_HOST=""
PG_PORT="5432"
PG_ADMIN_USER="postgres"
DB_NAME="openestate"
APP_PASSWORD=""
SYSTEM_PASSWORD=""
ENV_FILE="/etc/openestate/openestate.env"

while [ $# -gt 0 ]; do
  case "$1" in
    --host) PG_HOST="$2"; shift 2 ;;
    --port) PG_PORT="$2"; shift 2 ;;
    --admin-user) PG_ADMIN_USER="$2"; shift 2 ;;
    --db) DB_NAME="$2"; shift 2 ;;
    --app-password) APP_PASSWORD="$2"; shift 2 ;;
    --system-password) SYSTEM_PASSWORD="$2"; shift 2 ;;
    --env-file) ENV_FILE="$2"; shift 2 ;;
    -h|--help)
      cat <<'USAGE'
Usage: setup-database.sh [options]
  --host HOST              Postgres host (default: local peer auth via
                            `sudo -u postgres psql`, no host/TCP involved)
  --port PORT               Postgres port (default: 5432, only used with --host)
  --admin-user USER         Superuser to connect as (default: postgres)
  --db NAME                 Database name to create (default: openestate)
  --app-password PW         Password for the openestate_app role
  --system-password PW      Password for the openestate_system role
  --env-file PATH           Fallback source for the two passwords above if
                             not given as flags (default: /etc/openestate/openestate.env)

If --app-password/--system-password are omitted, they are read out of
--env-file's DATABASE_URL/DATABASE_URL_SYSTEM lines, so a fresh env file
generated by install-native.sh and the actual DB role passwords never
diverge. If --host is omitted, connects via local peer auth as the
`postgres` OS user (Ubuntu's default) — set PGPASSWORD and pass --host for
a remote server.
USAGE
      exit 0
      ;;
    *) die "Unknown argument: $1 (see --help)" ;;
  esac
done

extract_password() {
  # $1 = env var name (DATABASE_URL or DATABASE_URL_SYSTEM)
  [ -f "$ENV_FILE" ] || return 1
  local url
  url="$(grep -m1 "^${1}=" "$ENV_FILE" | cut -d= -f2-)"
  [ -n "$url" ] || return 1
  printf '%s' "$url" | sed -E 's#^[a-z]+://[^:]+:([^@]+)@.*#\1#'
}

if [ -z "$APP_PASSWORD" ]; then
  APP_PASSWORD="$(extract_password DATABASE_URL)" || die "No --app-password given and could not read DATABASE_URL from $ENV_FILE"
fi
if [ -z "$SYSTEM_PASSWORD" ]; then
  SYSTEM_PASSWORD="$(extract_password DATABASE_URL_SYSTEM)" || die "No --system-password given and could not read DATABASE_URL_SYSTEM from $ENV_FILE"
fi

if [ -n "$PG_HOST" ]; then
  command -v psql >/dev/null 2>&1 || die "psql client not found. Install it: sudo apt-get install -y postgresql-client"
  psql_admin() { psql -v ON_ERROR_STOP=1 -h "$PG_HOST" -p "$PG_PORT" -U "$PG_ADMIN_USER" "$@"; }
else
  command -v psql >/dev/null 2>&1 || die "psql client not found. Install it: sudo apt-get install -y postgresql-client"
  sudo -u postgres true 2>/dev/null || die "Cannot sudo to the 'postgres' OS user for local peer auth. Pass --host/--admin-user for a remote server, or run this script as root."
  psql_admin() { sudo -u postgres psql -v ON_ERROR_STOP=1 "$@"; }
fi

psql_admin -tAc "SELECT 1" postgres >/dev/null 2>&1 || die "Cannot connect to PostgreSQL. Check it is running and the connection details are correct."

log "Ensuring database '${DB_NAME}' exists..."
if ! psql_admin -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" postgres | grep -q 1; then
  psql_admin -c "CREATE DATABASE ${DB_NAME}" postgres
  log "Created database '${DB_NAME}'."
else
  log "Database '${DB_NAME}' already exists — leaving it in place."
fi

log "Creating/updating openestate_app and openestate_system roles..."
psql_admin --dbname "$DB_NAME" <<-EOSQL
  -- Tenant-scoped role (RLS enforced, no BYPASSRLS)
  DO \$\$
  BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'openestate_app') THEN
      CREATE ROLE openestate_app WITH LOGIN PASSWORD '${APP_PASSWORD}' NOINHERIT;
    ELSE
      ALTER ROLE openestate_app WITH LOGIN PASSWORD '${APP_PASSWORD}';
    END IF;
  END
  \$\$;

  -- System role (BYPASSRLS for cross-tenant operations, NOT superuser)
  DO \$\$
  BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'openestate_system') THEN
      CREATE ROLE openestate_system WITH LOGIN PASSWORD '${SYSTEM_PASSWORD}' NOSUPERUSER NOCREATEDB NOCREATEROLE BYPASSRLS;
    ELSE
      ALTER ROLE openestate_system WITH LOGIN PASSWORD '${SYSTEM_PASSWORD}';
    END IF;
  END
  \$\$;

  GRANT USAGE ON SCHEMA public TO openestate_app;
  GRANT USAGE ON SCHEMA public TO openestate_system;
  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO openestate_app;
  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO openestate_system;

  ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO openestate_app;
  ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO openestate_system;
  ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO openestate_app;
  ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO openestate_system;
EOSQL

log "Database setup complete."
